//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineShop.Resource.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;alert alert-danger&quot;&gt;{0}&lt;/div&gt;.
        /// </summary>
        internal static string HTML_ALERT_ERROR {
            get {
                return ResourceManager.GetString("HTML_ALERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;alert alert-info&quot;&gt;{0}&lt;/div&gt;.
        /// </summary>
        internal static string HTML_ALERT_INFO {
            get {
                return ResourceManager.GetString("HTML_ALERT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;alert alert-success&quot;&gt;{0}&lt;/div&gt;.
        /// </summary>
        internal static string HTML_ALERT_SUCCESS {
            get {
                return ResourceManager.GetString("HTML_ALERT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;alert alert-warning&quot;&gt;{0}&lt;/div&gt;.
        /// </summary>
        internal static string HTML_ALERT_WARNING {
            get {
                return ResourceManager.GetString("HTML_ALERT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu chưa đúng.
        /// </summary>
        internal static string MSG_ERROR_ENTER_DATA_FOR_FORM {
            get {
                return ResourceManager.GetString("MSG_ERROR_ENTER_DATA_FOR_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hỗ trợ đã được gửi. Chúng tôi chân thành cám ơn về điều này và liên hệ lại trong thời gian sớm nhất.
        /// </summary>
        internal static string MSG_THE_CONTACT_HAS_BEEN_UPDATED {
            get {
                return ResourceManager.GetString("MSG_THE_CONTACT_HAS_BEEN_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hỗ trợ gửi không thành công.
        /// </summary>
        internal static string MSG_THE_CONTACT_HAS_NOT_BEEN_UPDATED {
            get {
                return ResourceManager.GetString("MSG_THE_CONTACT_HAS_NOT_BEEN_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm tạo thành công..
        /// </summary>
        internal static string MSG_THE_PRODUCT_HAS_BEEN_CREATED {
            get {
                return ResourceManager.GetString("MSG_THE_PRODUCT_HAS_BEEN_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm được cập nhật..
        /// </summary>
        internal static string MSG_THE_PRODUCT_HAS_BEEN_UPDATED {
            get {
                return ResourceManager.GetString("MSG_THE_PRODUCT_HAS_BEEN_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm không tạo thành công..
        /// </summary>
        internal static string MSG_THE_PRODUCT_HAS_NOT_BEEN_CREATED {
            get {
                return ResourceManager.GetString("MSG_THE_PRODUCT_HAS_NOT_BEEN_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm không cập nhật thành công.
        /// </summary>
        internal static string MSG_THE_PRODUCT_HAS_NOT_UPDATED {
            get {
                return ResourceManager.GetString("MSG_THE_PRODUCT_HAS_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cấu hình website được cập nhật thành công.
        /// </summary>
        internal static string MSG_THE_SITE_CONFIGUARATION_HAS_BEEN_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_SITE_CONFIGUARATION_HAS_BEEN_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Images/{0}.
        /// </summary>
        internal static string SRC_CONTENT_IMAGE_DIR {
            get {
                return ResourceManager.GetString("SRC_CONTENT_IMAGE_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/{0}.
        /// </summary>
        internal static string SRC_IMAGES_DIR {
            get {
                return ResourceManager.GetString("SRC_IMAGES_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Products/large/{0}.
        /// </summary>
        internal static string SRC_IMAGES_PRODUCT_LARGE {
            get {
                return ResourceManager.GetString("SRC_IMAGES_PRODUCT_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Products/medium/{0}.
        /// </summary>
        internal static string SRC_IMAGES_PRODUCT_MEDIUM {
            get {
                return ResourceManager.GetString("SRC_IMAGES_PRODUCT_MEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Products/min/{0}.
        /// </summary>
        internal static string SRC_IMAGES_PRODUCT_MIN {
            get {
                return ResourceManager.GetString("SRC_IMAGES_PRODUCT_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/Products/small/{0}.
        /// </summary>
        internal static string SRC_IMAGES_PRODUCT_SMALL {
            get {
                return ResourceManager.GetString("SRC_IMAGES_PRODUCT_SMALL", resourceCulture);
            }
        }
    }
}
