//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogue
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SiteName { get; set; }
        public string SiteUrl { get; set; }
        public string EmailAdmin { get; set; }
        public string EmailSite { get; set; }
        public string Address { get; set; }
        public string Phones { get; set; }
        public string Facebook { get; set; }
        public string Youtube { get; set; }
        public string Twitter { get; set; }
        public long ManagerBy { get; set; }
        public string MetaDescriptions { get; set; }
        public string MetaKeywords { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Status { get; set; }
    }
}
