//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public long ProDetailId { get; set; }
        public long ProductId { get; set; }
        public double Size { get; set; }
        public double Weight { get; set; }
    }
}
