//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CategoryOfProduct
    {
        public long ID { get; set; }
        public string CategoryName { get; set; }
        public string MetaTitle { get; set; }
        public long ParentId { get; set; }
        public string ParentName { get; set; }
        public int CatalogueId { get; set; }
        public string CatalogueName { get; set; }
        public string CatalogueStatus { get; set; }
        public int Orders { get; set; }
        public string Title { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedByName { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescriptions { get; set; }
        public string Status { get; set; }
        public bool ShowOnHome { get; set; }
    }
}
