//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SiteMap
    {
        public long Id { get; set; }
        public string Alias { get; set; }
        public int IsCategory { get; set; }
        public string CategoryAlias { get; set; }
        public long CategoryID { get; set; }
        public int CatalogueId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string URL { get; set; }
    }
}
