//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới danh mục tin tức.
        /// </summary>
        public static string CATEGORY_CREATE_A_NEW {
            get {
                return ResourceManager.GetString("CATEGORY_CREATE_A_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Category_DisplayOrder {
            get {
                return ResourceManager.GetString("Category_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả SEO.
        /// </summary>
        public static string Category_MetaDescription {
            get {
                return ResourceManager.GetString("Category_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khoá.
        /// </summary>
        public static string Category_Metakeyword {
            get {
                return ResourceManager.GetString("Category_Metakeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Category_MetaTitle {
            get {
                return ResourceManager.GetString("Category_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục cha.
        /// </summary>
        public static string Category_ParentId {
            get {
                return ResourceManager.GetString("Category_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tên danh mục.
        /// </summary>
        public static string Category_RequiredName {
            get {
                return ResourceManager.GetString("Category_RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề seo.
        /// </summary>
        public static string Category_SeoTitle {
            get {
                return ResourceManager.GetString("Category_SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        public static string Category_ShowOnHome {
            get {
                return ResourceManager.GetString("Category_ShowOnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Category_Status {
            get {
                return ResourceManager.GetString("Category_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật danh mục tin tức.
        /// </summary>
        public static string CATEGORY_UPDATE {
            get {
                return ResourceManager.GetString("CATEGORY_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới danh mục tin tức không thành công..
        /// </summary>
        public static string InsertCategoryFailed {
            get {
                return ResourceManager.GetString("InsertCategoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bài viết mới.
        /// </summary>
        public static string LABEL_CREATE_NEW_CONTENT {
            get {
                return ResourceManager.GetString("LABEL_CREATE_NEW_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên website.
        /// </summary>
        public static string LABEL_SITE_NAME {
            get {
                return ResourceManager.GetString("LABEL_SITE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật #{0}.
        /// </summary>
        public static string LABEL_UPDATE {
            get {
                return ResourceManager.GetString("LABEL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu input chưa đúng. Vui lòng kiểm tra lại.
        /// </summary>
        public static string MSG_ERROR_ENTER_DATA_FOR_FORM {
            get {
                return ResourceManager.GetString("MSG_ERROR_ENTER_DATA_FOR_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tin tức đã tạo thành công.
        /// </summary>
        public static string MSG_THE_CATEGORY_HAS_CREATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_CATEGORY_HAS_CREATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tin tức đã tạo không thành công.
        /// </summary>
        public static string MSG_THE_CATEGORY_HAS_CREATED_UNSUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_CATEGORY_HAS_CREATED_UNSUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tin tức không tìm thấy.
        /// </summary>
        public static string MSG_THE_CATEGORY_HAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_THE_CATEGORY_HAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tin tức đã cập nhật thành công.
        /// </summary>
        public static string MSG_THE_CATEGORY_HAS_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_CATEGORY_HAS_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tin tức đã cập nhật không thành công.
        /// </summary>
        public static string MSG_THE_CATEGORY_HAS_UPDATED_UNSUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_CATEGORY_HAS_UPDATED_UNSUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết được tạo thành công.
        /// </summary>
        public static string MSG_THE_CONTENT_HAS_CREATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_CONTENT_HAS_CREATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết tạo không thành công.
        /// </summary>
        public static string MSG_THE_CONTENT_HAS_CREATED_UNSUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_CONTENT_HAS_CREATED_UNSUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết không tìm thấy trong hệ thống.
        /// </summary>
        public static string MSG_THE_CONTENT_HAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_THE_CONTENT_HAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết cập nhật thành công.
        /// </summary>
        public static string MSG_THE_CONTENT_HAS_UPDATED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_CONTENT_HAS_UPDATED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết cập nhật không thành công.
        /// </summary>
        public static string MSG_THE_CONTENT_HAS_UPDATED_UNSUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_THE_CONTENT_HAS_UPDATED_UNSUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin hỗ trợ không thành công.
        /// </summary>
        public static string SYSTEM_ERROR_ADDING_FEEDBACK_HAS_BEEN_FINISHED {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_ADDING_FEEDBACK_HAS_BEEN_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thì hành được entity.
        /// </summary>
        public static string SYSTEM_ERROR_EXECUTE_SAVECHANGE_IN_ENTITY {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_EXECUTE_SAVECHANGE_IN_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model truyền vào là null.
        /// </summary>
        public static string SYSTEM_ERROR_MODEL_IS_NULL {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_MODEL_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biến {0} truyền vào phải lớn hơn 0..
        /// </summary>
        public static string SYSTEM_ERROR_THE_PARAMETER_LARGE_ZERO {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_THE_PARAMETER_LARGE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin cấu hình hệ thống không thành công..
        /// </summary>
        public static string SYSTEM_ERROR_THE_UPDATING_WEBSITE_CONFI_HAS_BEEN_FINISHED {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_THE_UPDATING_WEBSITE_CONFI_HAS_BEEN_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
